version: "3.9"

services:
  localstack:
    image: localstack/localstack:4.9.2
    container_name: localstack-main
    ports:
      - "4566:4566"            # Edge port (quan trọng nhất)
      - "4510-4559:4510-4559"  # Optional – external service ports
    environment:
      - SERVICES=s3,sqs,lambda,dynamodb,cloudwatch,sts
      - DEFAULT_REGION=ap-southeast-1
      - DEBUG=1
    volumes:
      - "localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack-data: