version: "3.9"

services:
  localstack:
    image: localstack/localstack-pro:4.9.2
    container_name: localstack-main
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - DEFAULT_REGION=ap-southeast-1
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - "localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack-data:
